# Generated by Django 3.1 on 2020-09-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200905_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
    ]
