# Generated by Django 3.1 on 2020-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
