# Generated by Django 3.1 on 2020-09-06 20:14

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200906_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, help_text='other attachment (optional)', upload_to='attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='attach a flyer (optional)', upload_to='post_thumbnails'),
        ),
    ]
