# Generated by Django 3.1 on 2020-09-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200906_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.CharField(blank=True, help_text='Name of your organization (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, help_text='Other attachment (optional)', upload_to='attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Attach a flyer (optional)', upload_to='post_thumbnails'),
        ),
    ]
