# Generated by Django 3.1 on 2020-09-06 20:44

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200906_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(help_text='Contact email address', max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
