# Generated by Django 3.1 on 2020-09-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200906_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(help_text='Contact email address', max_length=70, null=True),
        ),
    ]
