# Generated by Django 3.1 on 2020-09-07 06:56

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200906_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
