# Generated by Django 3.1 on 2020-09-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200906_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, help_text='location of this activity (optional)', max_length=150),
        ),
    ]
