# Generated by Django 3.1 on 2020-09-08 22:13

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200908_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(help_text='Location of this activity (optional)', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
