# Generated by Django 3.1 on 2020-09-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200908_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
