# Generated by Django 3.1 on 2020-10-05 18:48

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0019_auto_20200912_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Contact email address', max_length=70, null=True)),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True)),
                ('message', models.TextField(help_text='Message to the recruitor', null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
